### PR TITLE
removed signed-url

### PR DESCRIPTION
**Pull request by delianides**
@jbaxleyiii @johnthepink 

Removed signed URL request from circle.

### CODE REVIEW

**Comment by johnthepink** [comment]
@drew did you just make the bucket public?

**Comment by johnthepink** [comment]
@delianides did you just make the bucket public?

**Comment by delianides** [comment]
@johnthepink pretty much, there's nothing there but the app, all credentials get loaded in later. So theres no real difference if someone cloned the repo and built their own version.

**Comment by johnthepink** [comment]
@delianides sounds good. i didn't do that initially just in case we had an accidental build with credentials in it, but you're right in theory it should happen

**Comment by delianides** [comment]
@johnthepink the main reason to do it is for rolling back deploys. Unless we could build the url signing into the container image or the shell script...It should be feasible if you give the ec2 instances the correct IAM permissions.

**Pull request merged**
